server:
  port: 8080

spring:
  application:
    name: seu-projeto-spring-boot
  data:
    mongodb:
      uri: mongodb://localhost:27017/seu_nome_de_banco
  jackson:
    serialization:
      write-dates-as-timestamps: false